name: APIFinancas-deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CAMINHO_PROJETO_TESTES: ./APIFinancas.Especificacoes
  CAMINHO_PROJETO_WEBAPP: ./APIFinancas
  NOME_WEBAPP_AZURE: anpfinancas
  NOME_DIR_PUBLICACAO: app
  NOME_ARTIFACT_PUBLICACAO: Publicacao_APIFinancas

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Executar testes automatizados
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal

    - name: Notificação de sucesso na execução
      if: success()
      shell: pwsh
      run: |
        $Execucao = '{ "workflow": "' + ${env:GITHUB_WORKFLOW} + '", "numExecucao": ' + ${env:GITHUB_RUN_NUMBER} + ' }'
        Write-Host $Execucao
        Invoke-RestMethod -Uri "${{ secrets.URL_LOGIC_APP_SUCESSO }}" -Method POST -ContentType "application/json" -Body $Execucao

    - name: Notificação de erro na execução
      if: failure()
      shell: pwsh
      run: |
        $Execucao = '{ "workflow": "' + ${env:GITHUB_WORKFLOW} + '", "numExecucao": ' + ${env:GITHUB_RUN_NUMBER} + ' }'
        Write-Host $Execucao
        Invoke-RestMethod -Uri "${{ secrets.URL_LOGIC_APP_FALHA }}" -Method POST -ContentType "application/json" -Body $Execucao

  publish:
    needs: [tests]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Publish com o utilitario dotnet
      run: dotnet publish ${{ env.CAMINHO_PROJETO_WEBAPP }} -c Release -o ${{ env.NOME_DIR_PUBLICACAO }}

    - name: Upload da Publicação como Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: ${{ env.NOME_ARTIFACT_PUBLICACAO }}
        path: ${{ env.NOME_DIR_PUBLICACAO }}

  deployment:
    needs: [publish]

    runs-on: ubuntu-latest
    
    steps:    
      - name: Download do Artifact contendo a Publicação
        uses: actions/download-artifact@v2.0.8
        with:
          name: ${{ env.NOME_ARTIFACT_PUBLICACAO }}
          path: ${{ env.NOME_DIR_PUBLICACAO }}
          
      - name: Login no Azure
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deployment no Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.NOME_WEBAPP_AZURE }}
          package: ${{ env.NOME_DIR_PUBLICACAO }}